platform :ios, '9.0'
inhibit_all_warnings!
install! 'cocoapods', :warn_for_multiple_pod_sources => false
use_frameworks!

require "bd_pod_extentions"
# 用于开启依赖解析加速的服务，true开启
bytedanceAnalyzeSpeed(true,:project_type => 'swift')
bd_use_app('thirdParty', 'public', 'toutiao')
bd_enable_DevelopMode
bd_fix_module_for_binary_pod!

source 'https://github.com/cocoapods/specs.git'
source 'git@code.byted.org:i18n_ios/i18n_ios_pods_specs.git'

target 'PodTest_Example' do
  pod 'PodTest', :path => '../'

  target 'PodTest_Tests' do
    inherit! :search_paths
    
  end
end
